### ISSUE TITLE
Jitpack fails to download SEED as dependency

### ISSUE THREAD

**Issue by racinmat** [KaptainWutax/SEED#2]
My `build.gradle` looks like this:
```
repositories {
    mavenCentral()
    maven {
        url "https://jitpack.io"
    }
}
dependencies {
    implementation 'com.github.KaptainWutax:SEED:c540b5224dbb4dc80fe8a25bfcfcf9383f635a0c'
}
```
but I'm getting following error when trying to build the project.
```
 Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.KaptainWutax:SEED:c540b5224dbb4dc80fe8a25bfcfcf9383f635a0c.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/KaptainWutax/SEED/c540b5224dbb4dc80fe8a25bfcfcf9383f635a0c/SEED-c540b5224dbb4dc80fe8a25bfcfcf9383f635a0c.pom
       - https://jitpack.io/com/github/KaptainWutax/SEED/c540b5224dbb4dc80fe8a25bfcfcf9383f635a0c/SEED-c540b5224dbb4dc80fe8a25bfcfcf9383f635a0c.pom
     Required by:
         project :
```
`https://jitpack.io/com/github/KaptainWutax/SEED/c540b5224dbb4dc80fe8a25bfcfcf9383f635a0c/SEED-c540b5224dbb4dc80fe8a25bfcfcf9383f635a0c.pom` returns 404.
Maybe I have misconfigured something but the jitpack is not loading.

https://jitpack.io/com/github/KaptainWutax/SEED/c540b5224dbb4dc80fe8a25bfcfcf9383f635a0c/ contains only `build.log`

The newest commit works.
```
dependencies {
    implementation 'com.github.KaptainWutax:SEED:aa652432588edf5dbdf583b254b361049da607e5'
}
```
works as charm.

**Comment by KaptainWutax** [comment]
Yea I saw that and didn't really understand what was going on, the latest commit fixed it indeed though.
